//! HuggingFace reference integration test for gated attention.
//!
//! Loads fixture files generated by `dev/hf_reference/gated_attention_ref.py`
//! and verifies that the Rust implementations of `deinterleave_q_gate` and
//! `apply_sigmoid_gate_scalar` match the PyTorch reference within 1e-4.
//!
//! Run:
//!   cargo test --test gated_attention_hf_test
//!
//! Regenerate fixtures:
//!   uv run python dev/hf_reference/gated_attention_ref.py

use lattice_inference::attention::gated::{apply_sigmoid_gate_scalar, deinterleave_q_gate};
use std::fs;
use std::path::{Path, PathBuf};

// ===================================================================
// Helpers
// ===================================================================

fn fixture_dir() -> PathBuf {
    // This file lives in crates/inference/tests/; fixtures are in tests/fixtures/.
    let manifest = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest).join("tests/fixtures/gated_attention")
}

fn load_f32_bin(path: &Path) -> Vec<f32> {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    assert_eq!(
        bytes.len() % 4,
        0,
        "file {} has {} bytes, not a multiple of 4",
        path.display(),
        bytes.len()
    );
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect()
}

fn load_meta(dir: &Path) -> (usize, usize) {
    let text = fs::read_to_string(dir.join("meta.txt"))
        .expect("meta.txt not found — run dev/hf_reference/gated_attention_ref.py first");
    let mut lines = text.lines();
    let num_heads: usize = lines
        .next()
        .expect("meta.txt: missing num_heads line")
        .trim()
        .parse()
        .expect("meta.txt: num_heads not a valid usize");
    let head_dim: usize = lines
        .next()
        .expect("meta.txt: missing head_dim line")
        .trim()
        .parse()
        .expect("meta.txt: head_dim not a valid usize");
    (num_heads, head_dim)
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch in max_abs_diff");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

// ===================================================================
// Tests
// ===================================================================

/// Verify `deinterleave_q_gate` matches the PyTorch reference within 1e-4.
///
/// The scalar implementation uses exact f32 arithmetic (no approximation),
/// so this should be bit-exact with the Python reference that uses the same
/// deterministic data generator and the same copy logic.
#[test]
fn test_deinterleave_matches_hf_reference() {
    let dir = fixture_dir();
    if !dir.exists() {
        eprintln!(
            "Skipping: fixture dir not found at {}. Run dev/hf_reference/gated_attention_ref.py.",
            dir.display()
        );
        return;
    }

    let (num_heads, head_dim) = load_meta(&dir);
    let q_dim = num_heads * head_dim;

    let q_and_gate = load_f32_bin(&dir.join("q_and_gate.bin"));
    let ref_q_buf = load_f32_bin(&dir.join("q_buf.bin"));
    let ref_gate_buf = load_f32_bin(&dir.join("gate_buf.bin"));

    assert_eq!(
        q_and_gate.len(),
        2 * q_dim,
        "q_and_gate.bin length mismatch"
    );
    assert_eq!(ref_q_buf.len(), q_dim, "q_buf.bin length mismatch");
    assert_eq!(ref_gate_buf.len(), q_dim, "gate_buf.bin length mismatch");

    let mut rust_q_buf = vec![0.0f32; q_dim];
    let mut rust_gate_buf = vec![0.0f32; q_dim];
    deinterleave_q_gate(
        &q_and_gate,
        &mut rust_q_buf,
        &mut rust_gate_buf,
        num_heads,
        head_dim,
    );

    let diff_q = max_abs_diff(&rust_q_buf, &ref_q_buf);
    let diff_gate = max_abs_diff(&rust_gate_buf, &ref_gate_buf);

    assert!(
        diff_q <= 1e-4,
        "q_buf: max_abs_diff={diff_q} vs HF reference exceeds 1e-4"
    );
    assert!(
        diff_gate <= 1e-4,
        "gate_buf: max_abs_diff={diff_gate} vs HF reference exceeds 1e-4"
    );
}

/// Verify `apply_sigmoid_gate_scalar` matches the PyTorch reference within 1e-4.
///
/// Both the Rust and Python paths use exact `exp` + division. The only source
/// of difference is f32 rounding order, which is well within 1e-4.
#[test]
fn test_sigmoid_gate_matches_hf_reference() {
    let dir = fixture_dir();
    if !dir.exists() {
        eprintln!(
            "Skipping: fixture dir not found at {}. Run dev/hf_reference/gated_attention_ref.py.",
            dir.display()
        );
        return;
    }

    let (num_heads, head_dim) = load_meta(&dir);
    let q_dim = num_heads * head_dim;

    let ref_gate_buf = load_f32_bin(&dir.join("gate_buf.bin"));
    let context_in = load_f32_bin(&dir.join("context_in.bin"));
    let ref_context_out = load_f32_bin(&dir.join("context_out.bin"));

    assert_eq!(ref_gate_buf.len(), q_dim, "gate_buf.bin length mismatch");
    assert_eq!(context_in.len(), q_dim, "context_in.bin length mismatch");
    assert_eq!(
        ref_context_out.len(),
        q_dim,
        "context_out.bin length mismatch"
    );

    let mut rust_context = context_in.clone();
    apply_sigmoid_gate_scalar(&mut rust_context, &ref_gate_buf);

    let diff = max_abs_diff(&rust_context, &ref_context_out);
    assert!(
        diff <= 1e-4,
        "context_out: max_abs_diff={diff} vs HF reference exceeds 1e-4"
    );
}

/// End-to-end test: deinterleave then apply gate, verify against reference.
///
/// Chains both operations as the model code does (deinterleave q_and_gate →
/// apply sigmoid gate to context using the extracted gate buffer).
#[test]
fn test_full_gated_pipeline_matches_hf_reference() {
    let dir = fixture_dir();
    if !dir.exists() {
        eprintln!(
            "Skipping: fixture dir not found at {}. Run dev/hf_reference/gated_attention_ref.py.",
            dir.display()
        );
        return;
    }

    let (num_heads, head_dim) = load_meta(&dir);
    let q_dim = num_heads * head_dim;

    let q_and_gate = load_f32_bin(&dir.join("q_and_gate.bin"));
    let context_in = load_f32_bin(&dir.join("context_in.bin"));
    let ref_context_out = load_f32_bin(&dir.join("context_out.bin"));

    // Step 1: deinterleave
    let mut q_buf = vec![0.0f32; q_dim];
    let mut gate_buf = vec![0.0f32; q_dim];
    deinterleave_q_gate(&q_and_gate, &mut q_buf, &mut gate_buf, num_heads, head_dim);

    // Step 2: apply gate
    let mut context = context_in.clone();
    apply_sigmoid_gate_scalar(&mut context, &gate_buf);

    let diff = max_abs_diff(&context, &ref_context_out);
    assert!(
        diff <= 1e-4,
        "full pipeline: max_abs_diff={diff} vs HF reference exceeds 1e-4"
    );
}
