//! ADR-069 S5b gate: real Qwen3.5-0.8B checkpoint, CPU-only, greedy-decode a
//! multimodal (image + text) prompt through `generate_multimodal_f16` and
//! compare the greedy continuation against the committed HF differential
//! golden. This is the CPU milestone gate — "vision reads an image, end to
//! end" — with no GPU/Metal involved (the #989 fixture was generated by HF
//! transformers on CPU/float32/1-thread/greedy).
//!
//! **Portability note.** On the reference machine all three greedy tokens match
//! the golden exactly (`[1919, 2099, 369]`). The gate is machine-portable rather
//! than exact-3/3 because lattice's macOS f16 forward runs every projection
//! through Accelerate `cblas_sgemm` (AMX), whose f32 accumulation order is not
//! bit-identical across Apple-Silicon generations. The first golden token has a
//! ~4.1-logit margin (asserted exactly), but the second is a measured ~0.07-logit
//! near-tie with the third token, which cross-machine jitter can swap. The
//! assertions below encode exactly which positions are robust; see the block at
//! the free-running comparison for the per-position rationale.
//!
//! **Fail-closed contract** (mirrors `vision_s3_vit_forward_test.rs` /
//! `vision_s4_merger_test.rs`): reuses their `LATTICE_VISION_S3_MODEL_DIR` /
//! `LATTICE_VISION_S3_GATE_ENFORCE` env vars rather than minting new ones —
//! S5b shares the same checkpoint. With the env var unset or pointing at a
//! missing path, this test prints a skip line and returns; with
//! `LATTICE_VISION_S3_GATE_ENFORCE=1` a missing/misconfigured checkpoint
//! panics instead of skipping. Requires the `f16` cargo feature (the
//! checkpoint's decoder weights are F16 in the fp16 safetensors shard).
//!
//! Run:
//! ```bash
//! LATTICE_VISION_S3_MODEL_DIR=~/.lattice/models/qwen3.5-0.8b \
//! cargo test --release -p lattice-inference --features f16 \
//!     --test vision_s5b_e2e_gate_test -- --nocapture
//! ```

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct TensorManifest {
    path: String,
    num_elements: usize,
    sha256: String,
}

#[derive(Deserialize)]
struct JsonFileManifest {
    path: String,
    sha256: String,
}

#[derive(Deserialize)]
struct Manifest {
    image_grid_thw: Vec<[u64; 3]>,
    num_image_placeholder_tokens: usize,
    vit_post_merger: TensorManifest,
    input_ids: JsonFileManifest,
    greedy_tokens: JsonFileManifest,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("vision")
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn load_manifest(dir: &Path) -> Manifest {
    let bytes = std::fs::read(dir.join("manifest.json")).expect("reading manifest.json");
    serde_json::from_slice(&bytes).expect("parsing manifest.json")
}

fn load_f32_tensor(dir: &Path, tm: &TensorManifest) -> Vec<f32> {
    let bytes =
        std::fs::read(dir.join(&tm.path)).unwrap_or_else(|e| panic!("reading {}: {e}", tm.path));
    assert_eq!(
        bytes.len(),
        tm.num_elements * 4,
        "{}: byte length mismatch",
        tm.path
    );
    assert_eq!(
        sha256_hex(&bytes),
        tm.sha256,
        "{}: sha256 mismatch vs manifest.json",
        tm.path
    );
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn load_json_checked(dir: &Path, jm: &JsonFileManifest) -> serde_json::Value {
    let bytes =
        std::fs::read(dir.join(&jm.path)).unwrap_or_else(|e| panic!("reading {}: {e}", jm.path));
    assert_eq!(
        sha256_hex(&bytes),
        jm.sha256,
        "{}: sha256 mismatch vs manifest.json",
        jm.path
    );
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parsing {}: {e}", jm.path))
}

fn enforce() -> bool {
    std::env::var("LATTICE_VISION_S3_GATE_ENFORCE").as_deref() == Ok("1")
}

fn shellexpand_home(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("~/")
        && let Ok(home) = std::env::var("HOME")
    {
        return format!("{home}/{rest}");
    }
    path.to_string()
}

fn require_env_model_dir() -> Option<PathBuf> {
    const VAR: &str = "LATTICE_VISION_S3_MODEL_DIR";
    match std::env::var(VAR) {
        Ok(value) => {
            let path = PathBuf::from(shellexpand_home(&value));
            if path.exists() {
                Some(path)
            } else if enforce() {
                panic!(
                    "{VAR}={} does not exist, and LATTICE_VISION_S3_GATE_ENFORCE=1 — \
                     the S5b e2e gate must fail closed on a missing checkpoint",
                    path.display()
                );
            } else {
                eprintln!(
                    "LATTICE_VISION_S5B_SKIPPED reason=missing_path {VAR}={}",
                    path.display()
                );
                None
            }
        }
        Err(_) if enforce() => panic!("{VAR} must be set when LATTICE_VISION_S3_GATE_ENFORCE=1"),
        Err(_) => {
            eprintln!("LATTICE_VISION_S5B_SKIPPED reason=unset_env {VAR}");
            None
        }
    }
}

/// Fixture-only check: the committed #989 vision golden parses, its recorded
/// sha256s match, and its anchor invariants hold. Runs unconditionally, no
/// checkpoint required (mirrors `vision_s3`'s pre-merger fixture check), which
/// also keeps the fixture loaders exercised without the `f16` feature.
#[test]
fn s5b_golden_fixture_is_valid() {
    let dir = fixture_dir();
    let manifest = load_manifest(&dir);

    // Post-merger visual rows: sha256 + byte length are checked inside the
    // loader; assert finiteness and that the element count is a whole number of
    // visual rows.
    let post_merger = load_f32_tensor(&dir, &manifest.vit_post_merger);
    assert!(post_merger.iter().all(|v| v.is_finite()));
    assert!(!manifest.image_grid_thw.is_empty());
    assert!(manifest.num_image_placeholder_tokens > 0);
    assert_eq!(
        post_merger.len() % manifest.num_image_placeholder_tokens,
        0,
        "post-merger element count is not a whole number of visual rows"
    );

    // Prompt + golden continuation: sha256 checked inside the loader; assert the
    // reviewed anchors so a silent fixture regeneration can't drift the gate.
    let input_ids = load_json_checked(&dir, &manifest.input_ids);
    assert_eq!(
        input_ids
            .as_array()
            .expect("input_ids.json is an array")
            .len(),
        82,
        "fixture prompt drifted from the reviewed anchor"
    );
    let greedy = load_json_checked(&dir, &manifest.greedy_tokens);
    let tokens: Vec<i64> = greedy["token_ids"]
        .as_array()
        .expect("greedy_tokens.token_ids")
        .iter()
        .map(|v| v.as_i64().expect("greedy token ids are integers"))
        .collect();
    assert!(tokens.len() >= 3);
    assert_eq!(
        &tokens[..3],
        &[1919, 2099, 369],
        "committed HF golden continuation drifted from the reviewed anchor"
    );
}

/// Resolve the safetensors file for `load_f16_weights`, which needs a single
/// `SafetensorsFile`. A local checkout may expose a convenience
/// `model.safetensors` (often a symlink), but a raw HuggingFace snapshot — what
/// CI materializes via `snapshot_download` — has only the sharded file(s) named
/// in `model.safetensors.index.json` and no plain `model.safetensors`. This
/// 0.8B checkpoint is a single shard, so fall back to the one shard the index
/// points at. Mirrors `Qwen35Model::from_safetensors`'s plain-then-index
/// precedence, but resolves the concrete shard path this single-file gate needs.
#[cfg(feature = "f16")]
fn resolve_safetensors_path(model_dir: &Path) -> PathBuf {
    let plain = model_dir.join("model.safetensors");
    if plain.exists() {
        return plain;
    }
    // Reuse the production strict index parser so this gate rejects exactly what
    // `Qwen35Model::from_safetensors` would. A loose `serde_json::Value` parse
    // silently drops a non-string shard value and keeps only the last of a
    // duplicated tensor-name key, so a malformed index could resolve to a shard
    // the runtime loader refuses — a fail-open the gate must not have.
    let index = lattice_inference::weights::parse_index(model_dir).unwrap_or_else(|e| {
        panic!(
            "no model.safetensors in {} and no valid model.safetensors.index.json: {e}",
            model_dir.display()
        )
    });
    let mut shards: Vec<&str> = index.weight_map.values().map(String::as_str).collect();
    shards.sort_unstable();
    shards.dedup();
    match shards.as_slice() {
        // Route through the same containment policy production loading uses
        // (`lattice_inference::weights::resolve_shard_path`), not a raw
        // `model_dir.join(one)` -- otherwise an index value like
        // `../outside/model.safetensors` would make this gate read outside
        // the checkpoint while production correctly rejects it, so the gate
        // could report parity against different weights than production
        // ever loads.
        [one] => {
            lattice_inference::weights::resolve_shard_path(model_dir, one).unwrap_or_else(|e| {
                panic!(
                    "shard '{one}' referenced by {} is invalid: {e}",
                    model_dir.join("model.safetensors.index.json").display()
                )
            })
        }
        [] => panic!(
            "empty weight_map in {}",
            model_dir.join("model.safetensors.index.json").display()
        ),
        _ => panic!(
            "multi-shard checkpoint ({} shards) is not supported by this single-file gate",
            shards.len()
        ),
    }
}

/// Strictness guards for `resolve_safetensors_path`: it must reject the malformed
/// indexes the runtime loader rejects, not silently accept them. Mutation-sensitive
/// against the prior loose `serde_json::Value` + `filter_map(as_str)` parse, which
/// dropped non-string values and collapsed duplicate keys. No checkpoint needed —
/// each case writes a tiny index into a temp dir.
#[cfg(feature = "f16")]
mod resolver_strictness_tests {
    use super::resolve_safetensors_path;
    use std::io::Write;
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicU64, Ordering};

    fn write_index(dir: &Path, body: &str) {
        std::fs::create_dir_all(dir).expect("create temp model dir");
        let mut f =
            std::fs::File::create(dir.join("model.safetensors.index.json")).expect("create index");
        f.write_all(body.as_bytes()).expect("write index");
    }

    fn tmp_dir(tag: &str) -> PathBuf {
        // Unique per process AND per invocation: a shared fixed name lets two
        // concurrent runs of this test binary on a shared machine delete or
        // overwrite each other's index, which could turn a malformed-index
        // rejection test into a false pass (the panic would come from a
        // concurrent deletion, not from strict parsing).
        static NONCE: AtomicU64 = AtomicU64::new(0);
        let n = NONCE.fetch_add(1, Ordering::Relaxed);
        let d =
            std::env::temp_dir().join(format!("lv_s5b_resolver_{tag}_{}_{n}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        d
    }

    fn resolve_result(dir: &Path) -> Result<PathBuf, Box<dyn std::any::Any + Send>> {
        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            resolve_safetensors_path(dir)
        }))
    }

    #[test]
    fn rejects_non_string_shard_value() {
        let dir = tmp_dir("nonstring");
        write_index(
            &dir,
            r#"{"weight_map":{"a":"model.safetensors-00001-of-00001.safetensors","b":123}}"#,
        );
        let r = resolve_result(&dir);
        std::fs::remove_dir_all(&dir).ok();
        assert!(
            r.is_err(),
            "a non-string shard value must be rejected, not silently dropped"
        );
    }

    #[test]
    fn rejects_duplicate_tensor_key() {
        let dir = tmp_dir("dupkey");
        write_index(
            &dir,
            r#"{"weight_map":{"a":"s1.safetensors","a":"s2.safetensors"}}"#,
        );
        let r = resolve_result(&dir);
        std::fs::remove_dir_all(&dir).ok();
        assert!(
            r.is_err(),
            "a duplicate tensor-name key must be rejected, not collapsed to the last value"
        );
    }

    #[test]
    fn accepts_single_shard_index() {
        let dir = tmp_dir("single");
        write_index(
            &dir,
            r#"{"weight_map":{"a":"only.safetensors","b":"only.safetensors"}}"#,
        );
        // `resolve_safetensors_path` now resolves through the same
        // containment policy as production (`resolve_shard_path`), which
        // canonicalizes the candidate and therefore requires it to exist —
        // so the shard file itself, not just the index entry naming it,
        // must be present for the accept case.
        std::fs::write(dir.join("only.safetensors"), b"stub").expect("write shard stub");
        let p = resolve_safetensors_path(&dir);
        let expected = std::fs::canonicalize(dir.join("only.safetensors"))
            .expect("canonicalize expected shard path");
        std::fs::remove_dir_all(&dir).ok();
        assert_eq!(p, expected);
    }
}

#[cfg(feature = "f16")]
fn run_s5b_gate(model_dir: &Path) {
    use lattice_inference::forward::cpu_f16::generate_multimodal_f16;
    use lattice_inference::model::qwen35_config::{GenerateConfig, Qwen35Config};
    use lattice_inference::vision::multimodal::Qwen35VisionRequest;
    use lattice_inference::vision::qwen35_vit::GridThw;
    use lattice_inference::weights::SafetensorsFile;
    use lattice_inference::weights::f16_weights::load_f16_weights;

    let dir = fixture_dir();
    let manifest = load_manifest(&dir);

    let post_merger = load_f32_tensor(&dir, &manifest.vit_post_merger);
    let input_ids_json = load_json_checked(&dir, &manifest.input_ids);
    let input_ids: Vec<u32> = input_ids_json
        .as_array()
        .expect("input_ids.json is an array")
        .iter()
        .map(|v| v.as_i64().expect("input_ids entries are integers") as u32)
        .collect();
    assert_eq!(
        input_ids.len(),
        82,
        "fixture prompt drifted from the reviewed anchor"
    );

    let greedy = load_json_checked(&dir, &manifest.greedy_tokens);
    let target_tokens: Vec<i64> = greedy["token_ids"]
        .as_array()
        .expect("greedy_tokens.token_ids")
        .iter()
        .map(|v| v.as_i64().expect("greedy token ids are integers"))
        .collect();

    let cfg = Qwen35Config::from_model_dir(model_dir).expect("0.8b config.json parses");
    let vision_cfg = cfg
        .vision_config
        .clone()
        .expect("Qwen3.5-0.8B checkpoint must carry a vision_config");
    let image_token_id = cfg
        .image_token_id
        .expect("checkpoint config.json must carry image_token_id");
    assert_eq!(
        image_token_id, 248_056,
        "image_token_id drifted from the reviewed anchor"
    );

    let image_grids: Vec<GridThw> = manifest
        .image_grid_thw
        .iter()
        .map(|&[t, h, w]| GridThw {
            t: t as usize,
            h: h as usize,
            w: w as usize,
        })
        .collect();

    let request = Qwen35VisionRequest {
        input_ids,
        image_grids,
        post_merger_rows: post_merger,
        image_token_id,
        spatial_merge_size: vision_cfg.spatial_merge_size,
        decoder_hidden_size: cfg.hidden_size,
    };
    request
        .validate()
        .expect("fixture-derived request is valid");
    assert_eq!(
        request.image_pad_count(),
        manifest.num_image_placeholder_tokens
    );

    let model_path = resolve_safetensors_path(model_dir);
    let sf = SafetensorsFile::open(&model_path).expect("opening the resolved safetensors file");
    let weights = load_f16_weights(&sf, &cfg).expect("real f16 decoder weights must load");

    // Pure greedy, matching the fixture's HF reference (manifest.json's `decode` section):
    // no repetition penalty, no top-k/top-p truncation before the temperature=0 argmax.
    let gen_cfg = GenerateConfig {
        max_new_tokens: 3,
        temperature: 0.0,
        repetition_penalty: 1.0,
        seed: Some(1),
        stop_token_ids: vec![],
        ..Default::default()
    };

    let out = generate_multimodal_f16(&weights, &cfg, &request, &gen_cfg)
        .expect("multimodal generate succeeds against the real checkpoint");

    let got: Vec<i64> = out.token_ids.iter().map(|&t| t as i64).collect();
    eprintln!(
        "LATTICE_VISION_S5B_GREEDY_TOKENS got={got:?} target={:?}",
        &target_tokens[..3]
    );
    assert_eq!(got.len(), 3, "gate must free-run exactly 3 greedy tokens");
    check_greedy_parity(&got, &target_tokens[..3])
        .unwrap_or_else(|e| panic!("ADR-069 S5b gate failed: {e}"));
}

/// Machine-portable greedy-parity check for the S5b gate over the first three
/// greedy token ids. Exact-3/3 is not portable because lattice's macOS f16
/// forward routes every projection through Accelerate `cblas_sgemm` (AMX), whose
/// f32 accumulation order is not bit-identical across Apple-Silicon generations —
/// so this encodes exactly which positions survive that ~0.1-logit jitter:
///
/// - **Position 0** — exact. Decode-independent (sampled from the last *prefill*
///   logits) and wide-margin (~4.1 logits over its runner-up). Reproducing it
///   exercises the whole vision→decoder pipeline (post-merger injection at the
///   `<|image_pad|>` slots, prefill M-RoPE coordinates, all decoder layers,
///   lm_head, argmax), far beyond any cross-machine jitter.
/// - **Position 1** — a **measured ~0.07-logit near-tie** between `target[1]` and
///   `target[2]` (22.377 vs 22.306 on the reference machine) while the third
///   contender is ~6.7 logits below both. Jitter can swap the two near-tied
///   tokens but cannot reach any third token, so either candidate is accepted and
///   anything else is a real regression.
/// - **Position 2** — exact **only when** position 1 kept the golden token: a
///   free-running near-tie flip at position 1 changes the decode history, so the
///   position-2 token past a flip is not comparable to the golden (left
///   informational; the decode-time M-RoPE coordinate itself is unit-tested via
///   `qwen35_mrope::decode_position` / `build_decode_cos_sin`).
fn check_greedy_parity(got: &[i64], target: &[i64]) -> Result<(), String> {
    if got.len() != 3 || target.len() != 3 {
        return Err(format!(
            "expected 3 tokens each (got {}, target {})",
            got.len(),
            target.len()
        ));
    }
    if got[0] != target[0] {
        return Err(format!(
            "position-0 token {} != HF golden {} (whole vision->decoder pipeline)",
            got[0], target[0]
        ));
    }
    if got[1] != target[1] && got[1] != target[2] {
        return Err(format!(
            "position-1 token {} is neither near-tie candidate ({} or {}); the 3rd \
             contender is ~6.7 logits away, out of jitter reach — real regression",
            got[1], target[1], target[2]
        ));
    }
    if got[1] == target[1] && got[2] != target[2] {
        return Err(format!(
            "with golden position-1 preserved, position-2 token {} != HF golden {}",
            got[2], target[2]
        ));
    }
    Ok(())
}

mod parity_logic_tests {
    use super::check_greedy_parity;

    // Reference golden continuation for the committed #989 fixture.
    const GOLDEN: [i64; 3] = [1919, 2099, 369];

    #[test]
    fn accepts_exact_reference() {
        assert!(check_greedy_parity(&[1919, 2099, 369], &GOLDEN).is_ok());
    }

    #[test]
    fn accepts_near_tie_flip_at_position_1() {
        // Position 1 flips to the near-tie runner-up (= GOLDEN[2]); position 2
        // then diverges (different decode history) and is deliberately not checked.
        assert!(check_greedy_parity(&[1919, 369, 42], &GOLDEN).is_ok());
    }

    #[test]
    fn rejects_position_0_regression() {
        assert!(check_greedy_parity(&[999, 2099, 369], &GOLDEN).is_err());
    }

    #[test]
    fn rejects_position_1_outside_near_tie() {
        assert!(check_greedy_parity(&[1919, 5000, 369], &GOLDEN).is_err());
    }

    #[test]
    fn rejects_position_2_regression_with_preserved_history() {
        assert!(check_greedy_parity(&[1919, 2099, 999], &GOLDEN).is_err());
    }
}

#[cfg(not(feature = "f16"))]
fn run_s5b_gate(_model_dir: &Path) {
    if enforce() {
        panic!(
            "LATTICE_VISION_S3_GATE_ENFORCE=1 but the `f16` feature is not enabled — the real \
             fp16 checkpoint's decoder weights require it"
        );
    }
    eprintln!("LATTICE_VISION_S5B_SKIPPED reason=f16_feature_disabled");
}

/// The S5b gate: real fp16 checkpoint -> `generate_multimodal_f16` -> greedy
/// continuation matches the committed HF golden `[1919, 2099, 369]` (position 0
/// exactly; positions 1-2 with the documented near-tie portability tolerance).
#[test]
fn qwen35_multimodal_generate_matches_hf_greedy_continuation() {
    let Some(model_dir) = require_env_model_dir() else {
        return;
    };
    run_s5b_gate(&model_dir);
}
