//! ADR-069 S5b gate: real Qwen3.5-0.8B checkpoint, CPU-only, greedy-decode a
//! multimodal (image + text) prompt through `generate_multimodal_f16` and
//! compare the first 3 greedy tokens against the committed HF differential
//! golden. This is the CPU-deterministic milestone gate — "vision reads an
//! image, end to end" — with no GPU/Metal involved (see CLAUDE.md's
//! CPU-first framing: the #989 fixture was generated by HF transformers on
//! CPU/float32/1-thread/greedy, so the parity target is exactly reproducible
//! locally on any machine with the checkpoint on disk).
//!
//! **Fail-closed contract** (mirrors `vision_s3_vit_forward_test.rs` /
//! `vision_s4_merger_test.rs`): reuses their `LATTICE_VISION_S3_MODEL_DIR` /
//! `LATTICE_VISION_S3_GATE_ENFORCE` env vars rather than minting new ones —
//! S5b shares the same checkpoint. With the env var unset or pointing at a
//! missing path, this test prints a skip line and returns; with
//! `LATTICE_VISION_S3_GATE_ENFORCE=1` a missing/misconfigured checkpoint
//! panics instead of skipping. Requires the `f16` cargo feature (the
//! checkpoint's decoder weights are F16 in the fp16 safetensors shard).
//!
//! Run:
//! ```bash
//! LATTICE_VISION_S3_MODEL_DIR=~/.lattice/models/qwen3.5-0.8b \
//! cargo test --release -p lattice-inference --features f16 \
//!     --test vision_s5b_e2e_gate_test -- --nocapture
//! ```

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct TensorManifest {
    path: String,
    num_elements: usize,
    sha256: String,
}

#[derive(Deserialize)]
struct JsonFileManifest {
    path: String,
    sha256: String,
}

#[derive(Deserialize)]
struct Manifest {
    image_grid_thw: Vec<[u64; 3]>,
    num_image_placeholder_tokens: usize,
    vit_post_merger: TensorManifest,
    input_ids: JsonFileManifest,
    greedy_tokens: JsonFileManifest,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("vision")
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn load_manifest(dir: &Path) -> Manifest {
    let bytes = std::fs::read(dir.join("manifest.json")).expect("reading manifest.json");
    serde_json::from_slice(&bytes).expect("parsing manifest.json")
}

fn load_f32_tensor(dir: &Path, tm: &TensorManifest) -> Vec<f32> {
    let bytes =
        std::fs::read(dir.join(&tm.path)).unwrap_or_else(|e| panic!("reading {}: {e}", tm.path));
    assert_eq!(
        bytes.len(),
        tm.num_elements * 4,
        "{}: byte length mismatch",
        tm.path
    );
    assert_eq!(
        sha256_hex(&bytes),
        tm.sha256,
        "{}: sha256 mismatch vs manifest.json",
        tm.path
    );
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn load_json_checked(dir: &Path, jm: &JsonFileManifest) -> serde_json::Value {
    let bytes =
        std::fs::read(dir.join(&jm.path)).unwrap_or_else(|e| panic!("reading {}: {e}", jm.path));
    assert_eq!(
        sha256_hex(&bytes),
        jm.sha256,
        "{}: sha256 mismatch vs manifest.json",
        jm.path
    );
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parsing {}: {e}", jm.path))
}

fn enforce() -> bool {
    std::env::var("LATTICE_VISION_S3_GATE_ENFORCE").as_deref() == Ok("1")
}

fn shellexpand_home(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("~/")
        && let Ok(home) = std::env::var("HOME")
    {
        return format!("{home}/{rest}");
    }
    path.to_string()
}

fn require_env_model_dir() -> Option<PathBuf> {
    const VAR: &str = "LATTICE_VISION_S3_MODEL_DIR";
    match std::env::var(VAR) {
        Ok(value) => {
            let path = PathBuf::from(shellexpand_home(&value));
            if path.exists() {
                Some(path)
            } else if enforce() {
                panic!(
                    "{VAR}={} does not exist, and LATTICE_VISION_S3_GATE_ENFORCE=1 — \
                     the S5b e2e gate must fail closed on a missing checkpoint",
                    path.display()
                );
            } else {
                eprintln!(
                    "LATTICE_VISION_S5B_SKIPPED reason=missing_path {VAR}={}",
                    path.display()
                );
                None
            }
        }
        Err(_) if enforce() => panic!("{VAR} must be set when LATTICE_VISION_S3_GATE_ENFORCE=1"),
        Err(_) => {
            eprintln!("LATTICE_VISION_S5B_SKIPPED reason=unset_env {VAR}");
            None
        }
    }
}

#[cfg(feature = "f16")]
fn run_s5b_gate(model_dir: &Path) {
    use lattice_inference::forward::cpu_f16::generate_multimodal_f16;
    use lattice_inference::model::qwen35_config::{GenerateConfig, Qwen35Config};
    use lattice_inference::vision::multimodal::Qwen35VisionRequest;
    use lattice_inference::vision::qwen35_vit::GridThw;
    use lattice_inference::weights::SafetensorsFile;
    use lattice_inference::weights::f16_weights::load_f16_weights;

    let dir = fixture_dir();
    let manifest = load_manifest(&dir);

    let post_merger = load_f32_tensor(&dir, &manifest.vit_post_merger);
    let input_ids_json = load_json_checked(&dir, &manifest.input_ids);
    let input_ids: Vec<u32> = input_ids_json
        .as_array()
        .expect("input_ids.json is an array")
        .iter()
        .map(|v| v.as_i64().expect("input_ids entries are integers") as u32)
        .collect();
    assert_eq!(
        input_ids.len(),
        82,
        "fixture prompt drifted from the reviewed anchor"
    );

    let greedy = load_json_checked(&dir, &manifest.greedy_tokens);
    let target_tokens: Vec<i64> = greedy["token_ids"]
        .as_array()
        .expect("greedy_tokens.token_ids")
        .iter()
        .map(|v| v.as_i64().expect("greedy token ids are integers"))
        .collect();

    let cfg = Qwen35Config::from_model_dir(model_dir).expect("0.8b config.json parses");
    let vision_cfg = cfg
        .vision_config
        .clone()
        .expect("Qwen3.5-0.8B checkpoint must carry a vision_config");
    let image_token_id = cfg
        .image_token_id
        .expect("checkpoint config.json must carry image_token_id");
    assert_eq!(
        image_token_id, 248_056,
        "image_token_id drifted from the reviewed anchor"
    );

    let image_grids: Vec<GridThw> = manifest
        .image_grid_thw
        .iter()
        .map(|&[t, h, w]| GridThw {
            t: t as usize,
            h: h as usize,
            w: w as usize,
        })
        .collect();

    let request = Qwen35VisionRequest {
        input_ids,
        image_grids,
        post_merger_rows: post_merger,
        image_token_id,
        spatial_merge_size: vision_cfg.spatial_merge_size,
        decoder_hidden_size: cfg.hidden_size,
    };
    request
        .validate()
        .expect("fixture-derived request is valid");
    assert_eq!(
        request.image_pad_count(),
        manifest.num_image_placeholder_tokens
    );

    let model_path = model_dir.join("model.safetensors");
    let sf = SafetensorsFile::open(&model_path).expect("opening model.safetensors");
    let weights = load_f16_weights(&sf, &cfg).expect("real f16 decoder weights must load");

    // Pure greedy, matching the fixture's HF reference (manifest.json's `decode` section):
    // no repetition penalty, no top-k/top-p truncation before the temperature=0 argmax.
    let gen_cfg = GenerateConfig {
        max_new_tokens: 3,
        temperature: 0.0,
        repetition_penalty: 1.0,
        seed: Some(1),
        stop_token_ids: vec![],
        ..Default::default()
    };

    let out = generate_multimodal_f16(&weights, &cfg, &request, &gen_cfg)
        .expect("multimodal generate succeeds against the real checkpoint");

    let got: Vec<i64> = out.token_ids.iter().map(|&t| t as i64).collect();
    eprintln!(
        "LATTICE_VISION_S5B_GREEDY_TOKENS got={got:?} target={:?}",
        &target_tokens[..3]
    );

    assert_eq!(
        got,
        target_tokens[..3],
        "ADR-069 S5b gate failed: first 3 greedy tokens {got:?} do not match the committed \
         HF golden {:?}",
        &target_tokens[..3]
    );
}

#[cfg(not(feature = "f16"))]
fn run_s5b_gate(_model_dir: &Path) {
    if enforce() {
        panic!(
            "LATTICE_VISION_S3_GATE_ENFORCE=1 but the `f16` feature is not enabled — the real \
             fp16 checkpoint's decoder weights require it"
        );
    }
    eprintln!("LATTICE_VISION_S5B_SKIPPED reason=f16_feature_disabled");
}

/// The S5b gate: real fp16 checkpoint -> `generate_multimodal_f16` -> first 3
/// greedy tokens == the committed HF golden `[1919, 2099, 369]`.
#[test]
fn qwen35_multimodal_generate_matches_hf_greedy_first_3_tokens() {
    let Some(model_dir) = require_env_model_dir() else {
        return;
    };
    run_s5b_gate(&model_dir);
}
